---
name: Build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          sudo apt install ninja-build
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Setup macOS
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        run: |
          brew install ninja
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Setup Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1

      - name: Create build directory
        shell: bash
        run: |
          mkdir build

      - name: Build & Test
        shell: bash
        working-directory: build
        run: |
          cmake ..
          cmake --build . --config Release
          ctest -VV -C Release
